### PR TITLE
Load 500 first langlinks for pages too

### PR DESCRIPTION
**Pull request by imustafin**
Langlinks are links to translations of a page ([MediaWiki API](https://www.mediawiki.org/wiki/API:Langlinks)). 

This patch adds `Page#langlinks` method which returns a hash `{ lang_code => title }`.

I changed `Client#request_page` to include langlinks in the result. This makes test fixtures (files in `/spec/fixtures/`) kinda invalid because they do not contain langlinks. For the test of `Page#langlinks` I made a new fixture of a new page. Should I update the current fixtures and update the tests for the new version or we leave them as they are?

### CODE REVIEW

**Comment by imustafin** [comment]
Checks fail because of #80

**Comment by pietromenna** [comment]
Hi @imustafin ,

Thank you very much for your PR. The tests are not passing.

I checked that you sent another PR (#80 ) which seems to fix the test. Would you mind to send the commit in the second PR to this PR? You can do this by adding the other commit to the branch you used in this pull request.

Let me know if you need further help.

**Comment by imustafin** [comment]
Like this?

**Comment by pietromenna** [comment]
Yes! Also, you could add an example to this file (https://github.com/kenpratt/wikipedia-client/blob/master/README.textile) and sign your work by adding your name to contributors :+1: 

What do you think about it?

**Comment by imustafin** [comment]
Done :relaxed:

**Pull request merged**
