### PR TITLE
Move from TravisCI to Github Actions

### LINKED ISSUE #91: Move away from travis-ci.org
travis-ci.org will be shut down soon. I suggest moving to Github Actions, or if for some reason, there is a desire to stay with travis, the account must be migrated to travis-ci.com.

If the move to Github Actions is a possibility, I don't mind implementing it.

### PR DESCRIPTION
**Pull request by DannyBen**
Closes #91

### CODE REVIEW

**Comment by DannyBen** [comment]
The Github actions will not run on this PR itself, as it seems. Needs to be merged first, then we can test with a dummy PR.

**Comment by kenpratt** [comment]
Looks good, thanks for investigating this.

**Comment by DannyBen** [comment]
BEA utiful.

image

**Comment by kenpratt** [comment]
Fancy!

**Pull request merged**
