### PR TITLE
Image thumburls

### PR DESCRIPTION
**Pull request by panaak**
as a response to #70 i tried to implement this. i'm not sure this is the right approach, but at least i tried..)

the default width is hard coded to Client, but could be added to the configuration directives i guess.

### CODE REVIEW

**Comment by panaak** [comment]
ok, not so good. i should have run the specs myself.. will do asap.

**Comment by pietromenna** [comment]
Hi @panaak ,

Thank you very much for your contribution! I am glad you took the opportunity to write a feature requested by others. The changes look ok, but I am missing unit tests for the new feature.

Let me know if you need some help with those.

**Comment by panaak** [comment]
OK, tests added and passing.

**Comment by pietromenna** [comment]
Thanks a lot @panaak !

**Pull request merged**
