### PR TITLE
Version bump to 1.13.0

### PR DESCRIPTION
**Pull request by kenpratt**
@DannyBen let me know if you're done with making changes and I can push a new version to RubyGems.

Also, added you to the contributors list -- if you'd prefer to not be on there, let me know and I'll remove that change.

### CODE REVIEW

**Comment by DannyBen** [comment]
That's fine, thanks :)

I am done for now, sure. Its important to get it published for ruby 2.7 and 3.0

**Comment by kenpratt** [comment]
Okay great, I'll go ahead and publish this, then.

**Comment by kenpratt** [comment]
Pushed to RubyGems: https://rubygems.org/gems/wikipedia-client

**Comment by DannyBen** [comment]
BTW - speaking about contributors, don't you prefer simply linking to https://github.com/kenpratt/wikipedia-client/graphs/contributors ?

**Comment by kenpratt** [comment]
I don't think any particular reason other than a very old codebase. I'll add the link to that section.

**Pull request merged**
