### PR TITLE
Fix a break caused by pages without images

### PR DESCRIPTION
**Pull request by henrywoody**
Wikipedia pages without images cause `image_metadata` to be `nil`. Thus, calling `.image_urls` or `.image_descriptionurls` ends in `NoMethodError: undefined method `map' for nil:NilClass`. This commit just modifies those methods so that they return `nil` if `image_metadata` is `nil`.

### CODE REVIEW

**Comment by pietromenna** [comment]
Hi @henrywoody ,

Would you mind to send me the example you used? I would like to add a test before merging so we ensure this feature is correctly tested.

**Comment by henrywoody** [comment]
Hello,

Yes no problem. I mean to add a test, but was having a bit of trouble working it in with your current tests and then I guess I forgot. Sorry about that!

In keeping with your Dijkstra example, the additional json elements should be as follows (these come from the 'pageimages' option included in prop):

"thumbnail":{"source":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Edsger_Wybe_Dijkstra.jpg/37px-Edsger_Wybe_Dijkstra.jpg","width":37,"height":50},"pageimage":"Edsger_Wybe_Dijkstra.jpg"

And when calling .main_image_url on the page object for Dijkstra should return ”https://upload.wikimedia.org/wikipedia/commons/d/d9/Edsger_Wybe_Dijkstra.jpg <https://upload.wikimedia.org/wikipedia/commons/d/d9/Edsger_Wybe_Dijkstra.jpg>”


For an additional example, calling .main_image_url on the wikipedia page https://en.wikipedia.org/wiki/Sealand_Dynasty <https://en.wikipedia.org/wiki/Sealand_Dynasty> should return nil since the page has no images.

Let me know if that’s enough or if that isn’t very clear/helpful or if I should/can do anything else to help out with this.

Best,
Henry

**Comment by henrywoody** [comment]
Hello,

I just realized that my method .main_image_url does not work properly for .tif files, due the way that they need to be displayed in the browser (I’ve noticed Wikipedia does this as .jpg).
I am sure that the method works for .png, .jpg, and .svg as I have encountered those and had success.

I have a “solution” for the .tif problem, but it involves handling .tifs as a specific case and using a hard-coded number of pixels (800) for display purposes, and I don’t think this is a great way to handle .tif files.  Since the .main_image_url method goes through the thumbnail image, the default size of the image (converted to .jpg) is very small (like 32px). I noticed that if you go through the pages manually the default is usually 800px, at least for US Presidents.
Here is an example image: https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/FDR_1944_Color_Portrait.tif/lossy-page1-800px-FDR_1944_Color_Portrait.tif.jpg <https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/FDR_1944_Color_Portrait.tif/lossy-page1-800px-FDR_1944_Color_Portrait.tif.jpg>

note: it seems you can put in nearly any number in for the “800px” from 1 to at least 2500.

I’m wondering if you have any ideas on how to handle this issue so that .tif file urls can come through in larger sizes but that is more dynamic that my current idea. Maybe an option of some sort that allows for entering preferred pixel num?

Best,
Henry

**Comment by pietromenna** [comment]
Hi @henrywoody . I just relaxed the rules class size for Rubocop on #65 .

**Comment by pietromenna** [comment]
First of all, thanks for your contribution!

I created a failing unit tests which creates the scenario you reported. Please, include the code described [here](https://github.com/pietromenna/wikipedia-client/tree/negative-test-for-64) with your Pull Request.

Now, the second problem (the tif one), I did not have time to look into that yet. We can create an issue and analyze further for a solution. What do you think of this approach?

Thanks once again for your contribution!

**Comment by henrywoody** [comment]
Of course, the gem has been very helpful for me and this was a method I needed as well. Happy to help!

I’ve just added that test to my code.

Yes that sounds, good. I’ll keep looking into the issue.

Best,
Henry

**Pull request merged**
